### PR TITLE
requestAnimationFrame instead of debounce

### PR DESCRIPTION
**Pull request by zslabs**
Gents - let's take a look at this in more detail to determine if this will provide more consistent results with the same or higher frame-rate. Reference http://www.html5rocks.com/en/tutorials/speed/animations/ to brush up on requestAnimationFrame()

### CODE REVIEW

**Comment by mfunkie** [comment]
We'll need a polyfill...

**Comment by zslabs** [comment]
yessir -- I believe https://gist.github.com/paulirish/1579671 would be the bit to use. Strongly think we should leave this out of the plugin and add it to the compatibility notes so users can decide what they want to support; while giving them an easy way to consume that polyfill.

**Comment by zslabs** [comment]
@mfunkie Added in compatibility section with reference to polyfill.

**Comment by zslabs** [comment]
@mfunkie Take a look at the latest addition. Uses an optimizedResize event that still uses requestAnimationFrame, but only fires when the window actually changes widths. Has fall-backs built-in for browsers that don't support requestAnimationFrame, but the polyfill mentioned will negate the fallback. Also updated README.

**Comment by mfunkie** [comment]
What exactly are we getting here by doing these changes?  debounce to 100ms almost certainly means the next call to refresh is going to happen on the next (or later) animation frame.  Do we need the larger list of callbacks to run on rAF in this optimizedResize when we're only calling one in the first place?

**Comment by zslabs** [comment]
The debounce is still firing on resize, which is going to run after the DOM manipulation is set. The idea here is (with requestAnimationFrame) is it fires "in-between" repaints to minimize the impact on the DOM. I don't think we'd need to parse this out to the larger set of functions as `update()` does the jam, but I'd leave that up to you and @jbenesch on any benefits for that. The idea here is we get the snappiness of not having any debounce at all, without the memory hit running an update function like that costs when hooking into the resize event.

**Comment by zslabs** [comment]
https://developer.mozilla.org/en-US/docs/Web/Events/resize in the "Example" section explains it a bit better.

**Comment by mfunkie** [comment]
All you're really gaining out of that pasted code is a `running` check so that the resize event only fires once per frame.  We don't need the list of callbacks that it maintains because we only add the one.

**Comment by zslabs** [comment]
That - and it's not queuing off the resize event, but requestAnimationFrame, which is the entire point of it. If we can simplify that logic that they recommended, then I'm all for it, but triggering your functions via requestAnimationFrame compared to the resize event is preferred.

**Comment by mfunkie** [comment]
I'm just saying that it could be replaced with something like

```js
var running = false;
window.addEventListener('resize', function resize() {
  if (!running) {
    running = true;
    if (window.requestAnimationFrame) {
      window.requestAnimationFrame(update);
    } else {
      setTimeout(update, 66);
    }
  }
});
```

**Comment by zslabs** [comment]
I'll see if I can get a timeline together so we can compare across the board. On our test page, we probably won't see much of a difference because it's a pretty dumbed-down use-case, but on the larger scale of our apps (especially with what I'm doing; I'll walk you through it), "when" we fire this stuff is key.

**Comment by withinboredom** [comment]
I would agree that with larger doms, *when* you update the dom has a huge impact.

**Pull request merged**
